services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema/mysql:/docker-entrypoint-initdb.d
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: api_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - api_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/api_mongodb --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.0
    container_name: redis
    command: redis-server --appendonly yes --requirepass password
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql_data:
  mongodb_data:
  redis_data:

networks:
  api_network:
    driver: bridge
